[package]
name = "bevy_test_game"
version = "0.1.0"
authors = ["Mike Hsu <mike.hsu@gmail.com>"]
edition = "2021"

[dependencies]
bevy = { version = "0.7" }
bevy_asset_ron = "0.4"
rand = "0.8.0"
ron = "0.6.4"
serde = { version = "1.0", features = ["derive"] }